# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'YXPlayerDemo' do
pod 'YXPlayerKit', '~> 1.0.1' 
pod 'Masonry'
end

target 'YXPlayerDemoTests' do

end

target 'YXPlayerDemoUITests' do

end

